name: widgetbook_sample
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  widgetbook_generator: ^3.7.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
